/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OutletRouteImport } from './routes/outlet'
import { Route as HostRouteImport } from './routes/host'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutletIndexRouteImport } from './routes/outlet.index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as AgencyIndexRouteImport } from './routes/agency.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OutletWorkspaceRouteImport } from './routes/outlet.workspace'
import { Route as OutletSubscriptionRouteImport } from './routes/outlet.subscription'
import { Route as OutletSpecialServiceRouteImport } from './routes/outlet.special-service'
import { Route as OutletSettingsRouteImport } from './routes/outlet.settings'
import { Route as OutletSalesRouteImport } from './routes/outlet.sales'
import { Route as OutletRatingsRouteImport } from './routes/outlet.ratings'
import { Route as OutletProfileRouteImport } from './routes/outlet.profile'
import { Route as OutletHistoryRouteImport } from './routes/outlet.history'
import { Route as OutletBookingsRouteImport } from './routes/outlet.bookings'
import { Route as OutletBillingRouteImport } from './routes/outlet.billing'
import { Route as HostWalletRouteImport } from './routes/host.wallet'
import { Route as HostTonightRouteImport } from './routes/host.tonight'
import { Route as HostSpecialServiceRouteImport } from './routes/host.special-service'
import { Route as HostSecurityRouteImport } from './routes/host.security'
import { Route as HostScanRouteImport } from './routes/host.scan'
import { Route as HostProfileRouteImport } from './routes/host.profile'
import { Route as HostHistoryRouteImport } from './routes/host.history'
import { Route as HostPaymentVoucherRouteImport } from './routes/host.PaymentVoucher'
import { Route as AgencySubscriptionRouteImport } from './routes/agency.subscription'
import { Route as AgencySpecialServiceRouteImport } from './routes/agency.special-service'
import { Route as AgencyRosterRouteImport } from './routes/agency.roster'
import { Route as AgencyPvRouteImport } from './routes/agency.pv'
import { Route as AgencyPrsRouteImport } from './routes/agency.prs'
import { Route as AgencyProfileRouteImport } from './routes/agency.profile'
import { Route as AgencyPendingRouteImport } from './routes/agency.pending'
import { Route as AgencyOutletsRouteImport } from './routes/agency.outlets'
import { Route as AgencyLiveRouteImport } from './routes/agency.live'
import { Route as AgencyHistoryRouteImport } from './routes/agency.history'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletIndexRoute = OutletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutletRoute,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const AgencyIndexRoute = AgencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencyRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OutletWorkspaceRoute = OutletWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => OutletRoute,
} as any)
const OutletSubscriptionRoute = OutletSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => OutletRoute,
} as any)
const OutletSpecialServiceRoute = OutletSpecialServiceRouteImport.update({
  id: '/special-service',
  path: '/special-service',
  getParentRoute: () => OutletRoute,
} as any)
const OutletSettingsRoute = OutletSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OutletRoute,
} as any)
const OutletSalesRoute = OutletSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => OutletRoute,
} as any)
const OutletRatingsRoute = OutletRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => OutletRoute,
} as any)
const OutletProfileRoute = OutletProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OutletRoute,
} as any)
const OutletHistoryRoute = OutletHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OutletRoute,
} as any)
const OutletBookingsRoute = OutletBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OutletRoute,
} as any)
const OutletBillingRoute = OutletBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OutletRoute,
} as any)
const HostWalletRoute = HostWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => HostRoute,
} as any)
const HostTonightRoute = HostTonightRouteImport.update({
  id: '/tonight',
  path: '/tonight',
  getParentRoute: () => HostRoute,
} as any)
const HostSpecialServiceRoute = HostSpecialServiceRouteImport.update({
  id: '/special-service',
  path: '/special-service',
  getParentRoute: () => HostRoute,
} as any)
const HostSecurityRoute = HostSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => HostRoute,
} as any)
const HostScanRoute = HostScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => HostRoute,
} as any)
const HostProfileRoute = HostProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HostRoute,
} as any)
const HostHistoryRoute = HostHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HostRoute,
} as any)
const HostPaymentVoucherRoute = HostPaymentVoucherRouteImport.update({
  id: '/PaymentVoucher',
  path: '/PaymentVoucher',
  getParentRoute: () => HostRoute,
} as any)
const AgencySubscriptionRoute = AgencySubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencySpecialServiceRoute = AgencySpecialServiceRouteImport.update({
  id: '/special-service',
  path: '/special-service',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyRosterRoute = AgencyRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyPvRoute = AgencyPvRouteImport.update({
  id: '/pv',
  path: '/pv',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyPrsRoute = AgencyPrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyProfileRoute = AgencyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyPendingRoute = AgencyPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyOutletsRoute = AgencyOutletsRouteImport.update({
  id: '/outlets',
  path: '/outlets',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyLiveRoute = AgencyLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyHistoryRoute = AgencyHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AgencyRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/outlet': typeof OutletRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/agency/history': typeof AgencyHistoryRoute
  '/agency/live': typeof AgencyLiveRoute
  '/agency/outlets': typeof AgencyOutletsRoute
  '/agency/pending': typeof AgencyPendingRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/agency/prs': typeof AgencyPrsRoute
  '/agency/pv': typeof AgencyPvRoute
  '/agency/roster': typeof AgencyRosterRoute
  '/agency/special-service': typeof AgencySpecialServiceRoute
  '/agency/subscription': typeof AgencySubscriptionRoute
  '/host/PaymentVoucher': typeof HostPaymentVoucherRoute
  '/host/history': typeof HostHistoryRoute
  '/host/profile': typeof HostProfileRoute
  '/host/scan': typeof HostScanRoute
  '/host/security': typeof HostSecurityRoute
  '/host/special-service': typeof HostSpecialServiceRoute
  '/host/tonight': typeof HostTonightRoute
  '/host/wallet': typeof HostWalletRoute
  '/outlet/billing': typeof OutletBillingRoute
  '/outlet/bookings': typeof OutletBookingsRoute
  '/outlet/history': typeof OutletHistoryRoute
  '/outlet/profile': typeof OutletProfileRoute
  '/outlet/ratings': typeof OutletRatingsRoute
  '/outlet/sales': typeof OutletSalesRoute
  '/outlet/settings': typeof OutletSettingsRoute
  '/outlet/special-service': typeof OutletSpecialServiceRoute
  '/outlet/subscription': typeof OutletSubscriptionRoute
  '/outlet/workspace': typeof OutletWorkspaceRoute
  '/admin/': typeof AdminIndexRoute
  '/agency/': typeof AgencyIndexRoute
  '/host/': typeof HostIndexRoute
  '/outlet/': typeof OutletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/agency/history': typeof AgencyHistoryRoute
  '/agency/live': typeof AgencyLiveRoute
  '/agency/outlets': typeof AgencyOutletsRoute
  '/agency/pending': typeof AgencyPendingRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/agency/prs': typeof AgencyPrsRoute
  '/agency/pv': typeof AgencyPvRoute
  '/agency/roster': typeof AgencyRosterRoute
  '/agency/special-service': typeof AgencySpecialServiceRoute
  '/agency/subscription': typeof AgencySubscriptionRoute
  '/host/PaymentVoucher': typeof HostPaymentVoucherRoute
  '/host/history': typeof HostHistoryRoute
  '/host/profile': typeof HostProfileRoute
  '/host/scan': typeof HostScanRoute
  '/host/security': typeof HostSecurityRoute
  '/host/special-service': typeof HostSpecialServiceRoute
  '/host/tonight': typeof HostTonightRoute
  '/host/wallet': typeof HostWalletRoute
  '/outlet/billing': typeof OutletBillingRoute
  '/outlet/bookings': typeof OutletBookingsRoute
  '/outlet/history': typeof OutletHistoryRoute
  '/outlet/profile': typeof OutletProfileRoute
  '/outlet/ratings': typeof OutletRatingsRoute
  '/outlet/sales': typeof OutletSalesRoute
  '/outlet/settings': typeof OutletSettingsRoute
  '/outlet/special-service': typeof OutletSpecialServiceRoute
  '/outlet/subscription': typeof OutletSubscriptionRoute
  '/outlet/workspace': typeof OutletWorkspaceRoute
  '/admin': typeof AdminIndexRoute
  '/agency': typeof AgencyIndexRoute
  '/host': typeof HostIndexRoute
  '/outlet': typeof OutletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agency': typeof AgencyRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/outlet': typeof OutletRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/agency/history': typeof AgencyHistoryRoute
  '/agency/live': typeof AgencyLiveRoute
  '/agency/outlets': typeof AgencyOutletsRoute
  '/agency/pending': typeof AgencyPendingRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/agency/prs': typeof AgencyPrsRoute
  '/agency/pv': typeof AgencyPvRoute
  '/agency/roster': typeof AgencyRosterRoute
  '/agency/special-service': typeof AgencySpecialServiceRoute
  '/agency/subscription': typeof AgencySubscriptionRoute
  '/host/PaymentVoucher': typeof HostPaymentVoucherRoute
  '/host/history': typeof HostHistoryRoute
  '/host/profile': typeof HostProfileRoute
  '/host/scan': typeof HostScanRoute
  '/host/security': typeof HostSecurityRoute
  '/host/special-service': typeof HostSpecialServiceRoute
  '/host/tonight': typeof HostTonightRoute
  '/host/wallet': typeof HostWalletRoute
  '/outlet/billing': typeof OutletBillingRoute
  '/outlet/bookings': typeof OutletBookingsRoute
  '/outlet/history': typeof OutletHistoryRoute
  '/outlet/profile': typeof OutletProfileRoute
  '/outlet/ratings': typeof OutletRatingsRoute
  '/outlet/sales': typeof OutletSalesRoute
  '/outlet/settings': typeof OutletSettingsRoute
  '/outlet/special-service': typeof OutletSpecialServiceRoute
  '/outlet/subscription': typeof OutletSubscriptionRoute
  '/outlet/workspace': typeof OutletWorkspaceRoute
  '/admin/': typeof AdminIndexRoute
  '/agency/': typeof AgencyIndexRoute
  '/host/': typeof HostIndexRoute
  '/outlet/': typeof OutletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agency'
    | '/host'
    | '/outlet'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/admin/jobs'
    | '/admin/subscriptions'
    | '/agency/history'
    | '/agency/live'
    | '/agency/outlets'
    | '/agency/pending'
    | '/agency/profile'
    | '/agency/prs'
    | '/agency/pv'
    | '/agency/roster'
    | '/agency/special-service'
    | '/agency/subscription'
    | '/host/PaymentVoucher'
    | '/host/history'
    | '/host/profile'
    | '/host/scan'
    | '/host/security'
    | '/host/special-service'
    | '/host/tonight'
    | '/host/wallet'
    | '/outlet/billing'
    | '/outlet/bookings'
    | '/outlet/history'
    | '/outlet/profile'
    | '/outlet/ratings'
    | '/outlet/sales'
    | '/outlet/settings'
    | '/outlet/special-service'
    | '/outlet/subscription'
    | '/outlet/workspace'
    | '/admin/'
    | '/agency/'
    | '/host/'
    | '/outlet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/admin/jobs'
    | '/admin/subscriptions'
    | '/agency/history'
    | '/agency/live'
    | '/agency/outlets'
    | '/agency/pending'
    | '/agency/profile'
    | '/agency/prs'
    | '/agency/pv'
    | '/agency/roster'
    | '/agency/special-service'
    | '/agency/subscription'
    | '/host/PaymentVoucher'
    | '/host/history'
    | '/host/profile'
    | '/host/scan'
    | '/host/security'
    | '/host/special-service'
    | '/host/tonight'
    | '/host/wallet'
    | '/outlet/billing'
    | '/outlet/bookings'
    | '/outlet/history'
    | '/outlet/profile'
    | '/outlet/ratings'
    | '/outlet/sales'
    | '/outlet/settings'
    | '/outlet/special-service'
    | '/outlet/subscription'
    | '/outlet/workspace'
    | '/admin'
    | '/agency'
    | '/host'
    | '/outlet'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agency'
    | '/host'
    | '/outlet'
    | '/register'
    | '/reset-password'
    | '/signin'
    | '/admin/jobs'
    | '/admin/subscriptions'
    | '/agency/history'
    | '/agency/live'
    | '/agency/outlets'
    | '/agency/pending'
    | '/agency/profile'
    | '/agency/prs'
    | '/agency/pv'
    | '/agency/roster'
    | '/agency/special-service'
    | '/agency/subscription'
    | '/host/PaymentVoucher'
    | '/host/history'
    | '/host/profile'
    | '/host/scan'
    | '/host/security'
    | '/host/special-service'
    | '/host/tonight'
    | '/host/wallet'
    | '/outlet/billing'
    | '/outlet/bookings'
    | '/outlet/history'
    | '/outlet/profile'
    | '/outlet/ratings'
    | '/outlet/sales'
    | '/outlet/settings'
    | '/outlet/special-service'
    | '/outlet/subscription'
    | '/outlet/workspace'
    | '/admin/'
    | '/agency/'
    | '/host/'
    | '/outlet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgencyRoute: typeof AgencyRouteWithChildren
  HostRoute: typeof HostRouteWithChildren
  OutletRoute: typeof OutletRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet': {
      id: '/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet/': {
      id: '/outlet/'
      path: '/'
      fullPath: '/outlet/'
      preLoaderRoute: typeof OutletIndexRouteImport
      parentRoute: typeof OutletRoute
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/agency/': {
      id: '/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AgencyIndexRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/outlet/workspace': {
      id: '/outlet/workspace'
      path: '/workspace'
      fullPath: '/outlet/workspace'
      preLoaderRoute: typeof OutletWorkspaceRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/subscription': {
      id: '/outlet/subscription'
      path: '/subscription'
      fullPath: '/outlet/subscription'
      preLoaderRoute: typeof OutletSubscriptionRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/special-service': {
      id: '/outlet/special-service'
      path: '/special-service'
      fullPath: '/outlet/special-service'
      preLoaderRoute: typeof OutletSpecialServiceRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/settings': {
      id: '/outlet/settings'
      path: '/settings'
      fullPath: '/outlet/settings'
      preLoaderRoute: typeof OutletSettingsRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/sales': {
      id: '/outlet/sales'
      path: '/sales'
      fullPath: '/outlet/sales'
      preLoaderRoute: typeof OutletSalesRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/ratings': {
      id: '/outlet/ratings'
      path: '/ratings'
      fullPath: '/outlet/ratings'
      preLoaderRoute: typeof OutletRatingsRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/profile': {
      id: '/outlet/profile'
      path: '/profile'
      fullPath: '/outlet/profile'
      preLoaderRoute: typeof OutletProfileRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/history': {
      id: '/outlet/history'
      path: '/history'
      fullPath: '/outlet/history'
      preLoaderRoute: typeof OutletHistoryRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/bookings': {
      id: '/outlet/bookings'
      path: '/bookings'
      fullPath: '/outlet/bookings'
      preLoaderRoute: typeof OutletBookingsRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/billing': {
      id: '/outlet/billing'
      path: '/billing'
      fullPath: '/outlet/billing'
      preLoaderRoute: typeof OutletBillingRouteImport
      parentRoute: typeof OutletRoute
    }
    '/host/wallet': {
      id: '/host/wallet'
      path: '/wallet'
      fullPath: '/host/wallet'
      preLoaderRoute: typeof HostWalletRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/tonight': {
      id: '/host/tonight'
      path: '/tonight'
      fullPath: '/host/tonight'
      preLoaderRoute: typeof HostTonightRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/special-service': {
      id: '/host/special-service'
      path: '/special-service'
      fullPath: '/host/special-service'
      preLoaderRoute: typeof HostSpecialServiceRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/security': {
      id: '/host/security'
      path: '/security'
      fullPath: '/host/security'
      preLoaderRoute: typeof HostSecurityRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/scan': {
      id: '/host/scan'
      path: '/scan'
      fullPath: '/host/scan'
      preLoaderRoute: typeof HostScanRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/profile': {
      id: '/host/profile'
      path: '/profile'
      fullPath: '/host/profile'
      preLoaderRoute: typeof HostProfileRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/history': {
      id: '/host/history'
      path: '/history'
      fullPath: '/host/history'
      preLoaderRoute: typeof HostHistoryRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/PaymentVoucher': {
      id: '/host/PaymentVoucher'
      path: '/PaymentVoucher'
      fullPath: '/host/PaymentVoucher'
      preLoaderRoute: typeof HostPaymentVoucherRouteImport
      parentRoute: typeof HostRoute
    }
    '/agency/subscription': {
      id: '/agency/subscription'
      path: '/subscription'
      fullPath: '/agency/subscription'
      preLoaderRoute: typeof AgencySubscriptionRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/special-service': {
      id: '/agency/special-service'
      path: '/special-service'
      fullPath: '/agency/special-service'
      preLoaderRoute: typeof AgencySpecialServiceRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/roster': {
      id: '/agency/roster'
      path: '/roster'
      fullPath: '/agency/roster'
      preLoaderRoute: typeof AgencyRosterRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/pv': {
      id: '/agency/pv'
      path: '/pv'
      fullPath: '/agency/pv'
      preLoaderRoute: typeof AgencyPvRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/prs': {
      id: '/agency/prs'
      path: '/prs'
      fullPath: '/agency/prs'
      preLoaderRoute: typeof AgencyPrsRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/profile': {
      id: '/agency/profile'
      path: '/profile'
      fullPath: '/agency/profile'
      preLoaderRoute: typeof AgencyProfileRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/pending': {
      id: '/agency/pending'
      path: '/pending'
      fullPath: '/agency/pending'
      preLoaderRoute: typeof AgencyPendingRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/outlets': {
      id: '/agency/outlets'
      path: '/outlets'
      fullPath: '/agency/outlets'
      preLoaderRoute: typeof AgencyOutletsRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/live': {
      id: '/agency/live'
      path: '/live'
      fullPath: '/agency/live'
      preLoaderRoute: typeof AgencyLiveRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/history': {
      id: '/agency/history'
      path: '/history'
      fullPath: '/agency/history'
      preLoaderRoute: typeof AgencyHistoryRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminJobsRoute: typeof AdminJobsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminJobsRoute: AdminJobsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgencyRouteChildren {
  AgencyHistoryRoute: typeof AgencyHistoryRoute
  AgencyLiveRoute: typeof AgencyLiveRoute
  AgencyOutletsRoute: typeof AgencyOutletsRoute
  AgencyPendingRoute: typeof AgencyPendingRoute
  AgencyProfileRoute: typeof AgencyProfileRoute
  AgencyPrsRoute: typeof AgencyPrsRoute
  AgencyPvRoute: typeof AgencyPvRoute
  AgencyRosterRoute: typeof AgencyRosterRoute
  AgencySpecialServiceRoute: typeof AgencySpecialServiceRoute
  AgencySubscriptionRoute: typeof AgencySubscriptionRoute
  AgencyIndexRoute: typeof AgencyIndexRoute
}

const AgencyRouteChildren: AgencyRouteChildren = {
  AgencyHistoryRoute: AgencyHistoryRoute,
  AgencyLiveRoute: AgencyLiveRoute,
  AgencyOutletsRoute: AgencyOutletsRoute,
  AgencyPendingRoute: AgencyPendingRoute,
  AgencyProfileRoute: AgencyProfileRoute,
  AgencyPrsRoute: AgencyPrsRoute,
  AgencyPvRoute: AgencyPvRoute,
  AgencyRosterRoute: AgencyRosterRoute,
  AgencySpecialServiceRoute: AgencySpecialServiceRoute,
  AgencySubscriptionRoute: AgencySubscriptionRoute,
  AgencyIndexRoute: AgencyIndexRoute,
}

const AgencyRouteWithChildren =
  AgencyRoute._addFileChildren(AgencyRouteChildren)

interface HostRouteChildren {
  HostPaymentVoucherRoute: typeof HostPaymentVoucherRoute
  HostHistoryRoute: typeof HostHistoryRoute
  HostProfileRoute: typeof HostProfileRoute
  HostScanRoute: typeof HostScanRoute
  HostSecurityRoute: typeof HostSecurityRoute
  HostSpecialServiceRoute: typeof HostSpecialServiceRoute
  HostTonightRoute: typeof HostTonightRoute
  HostWalletRoute: typeof HostWalletRoute
  HostIndexRoute: typeof HostIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostPaymentVoucherRoute: HostPaymentVoucherRoute,
  HostHistoryRoute: HostHistoryRoute,
  HostProfileRoute: HostProfileRoute,
  HostScanRoute: HostScanRoute,
  HostSecurityRoute: HostSecurityRoute,
  HostSpecialServiceRoute: HostSpecialServiceRoute,
  HostTonightRoute: HostTonightRoute,
  HostWalletRoute: HostWalletRoute,
  HostIndexRoute: HostIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

interface OutletRouteChildren {
  OutletBillingRoute: typeof OutletBillingRoute
  OutletBookingsRoute: typeof OutletBookingsRoute
  OutletHistoryRoute: typeof OutletHistoryRoute
  OutletProfileRoute: typeof OutletProfileRoute
  OutletRatingsRoute: typeof OutletRatingsRoute
  OutletSalesRoute: typeof OutletSalesRoute
  OutletSettingsRoute: typeof OutletSettingsRoute
  OutletSpecialServiceRoute: typeof OutletSpecialServiceRoute
  OutletSubscriptionRoute: typeof OutletSubscriptionRoute
  OutletWorkspaceRoute: typeof OutletWorkspaceRoute
  OutletIndexRoute: typeof OutletIndexRoute
}

const OutletRouteChildren: OutletRouteChildren = {
  OutletBillingRoute: OutletBillingRoute,
  OutletBookingsRoute: OutletBookingsRoute,
  OutletHistoryRoute: OutletHistoryRoute,
  OutletProfileRoute: OutletProfileRoute,
  OutletRatingsRoute: OutletRatingsRoute,
  OutletSalesRoute: OutletSalesRoute,
  OutletSettingsRoute: OutletSettingsRoute,
  OutletSpecialServiceRoute: OutletSpecialServiceRoute,
  OutletSubscriptionRoute: OutletSubscriptionRoute,
  OutletWorkspaceRoute: OutletWorkspaceRoute,
  OutletIndexRoute: OutletIndexRoute,
}

const OutletRouteWithChildren =
  OutletRoute._addFileChildren(OutletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgencyRoute: AgencyRouteWithChildren,
  HostRoute: HostRouteWithChildren,
  OutletRoute: OutletRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
