/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OutletRouteImport } from './routes/outlet'
import { Route as HostRouteImport } from './routes/host'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutletIndexRouteImport } from './routes/outlet.index'
import { Route as HostIndexRouteImport } from './routes/host.index'
import { Route as AgencyIndexRouteImport } from './routes/agency.index'
import { Route as OutletSalesRouteImport } from './routes/outlet.sales'
import { Route as OutletRatingsRouteImport } from './routes/outlet.ratings'
import { Route as OutletProfileRouteImport } from './routes/outlet.profile'
import { Route as OutletHistoryRouteImport } from './routes/outlet.history'
import { Route as OutletBookingsRouteImport } from './routes/outlet.bookings'
import { Route as OutletBillingRouteImport } from './routes/outlet.billing'
import { Route as HostWalletRouteImport } from './routes/host.wallet'
import { Route as HostTonightRouteImport } from './routes/host.tonight'
import { Route as HostScanRouteImport } from './routes/host.scan'
import { Route as HostProfileRouteImport } from './routes/host.profile'
import { Route as HostHistoryRouteImport } from './routes/host.history'
import { Route as AgencyRosterRouteImport } from './routes/agency.roster'
import { Route as AgencyReportsRouteImport } from './routes/agency.reports'
import { Route as AgencyPvRouteImport } from './routes/agency.pv'
import { Route as AgencyPrsRouteImport } from './routes/agency.prs'
import { Route as AgencyProfileRouteImport } from './routes/agency.profile'
import { Route as AgencyPendingRouteImport } from './routes/agency.pending'
import { Route as AgencyLiveRouteImport } from './routes/agency.live'
import { Route as AgencyHistoryRouteImport } from './routes/agency.history'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletRoute = OutletRouteImport.update({
  id: '/outlet',
  path: '/outlet',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletIndexRoute = OutletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OutletRoute,
} as any)
const HostIndexRoute = HostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostRoute,
} as any)
const AgencyIndexRoute = AgencyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgencyRoute,
} as any)
const OutletSalesRoute = OutletSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => OutletRoute,
} as any)
const OutletRatingsRoute = OutletRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => OutletRoute,
} as any)
const OutletProfileRoute = OutletProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OutletRoute,
} as any)
const OutletHistoryRoute = OutletHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OutletRoute,
} as any)
const OutletBookingsRoute = OutletBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OutletRoute,
} as any)
const OutletBillingRoute = OutletBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OutletRoute,
} as any)
const HostWalletRoute = HostWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => HostRoute,
} as any)
const HostTonightRoute = HostTonightRouteImport.update({
  id: '/tonight',
  path: '/tonight',
  getParentRoute: () => HostRoute,
} as any)
const HostScanRoute = HostScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => HostRoute,
} as any)
const HostProfileRoute = HostProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HostRoute,
} as any)
const HostHistoryRoute = HostHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => HostRoute,
} as any)
const AgencyRosterRoute = AgencyRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyReportsRoute = AgencyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyPvRoute = AgencyPvRouteImport.update({
  id: '/pv',
  path: '/pv',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyPrsRoute = AgencyPrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyProfileRoute = AgencyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyPendingRoute = AgencyPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyLiveRoute = AgencyLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AgencyRoute,
} as any)
const AgencyHistoryRoute = AgencyHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AgencyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/outlet': typeof OutletRouteWithChildren
  '/signin': typeof SigninRoute
  '/agency/history': typeof AgencyHistoryRoute
  '/agency/live': typeof AgencyLiveRoute
  '/agency/pending': typeof AgencyPendingRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/agency/prs': typeof AgencyPrsRoute
  '/agency/pv': typeof AgencyPvRoute
  '/agency/reports': typeof AgencyReportsRoute
  '/agency/roster': typeof AgencyRosterRoute
  '/host/history': typeof HostHistoryRoute
  '/host/profile': typeof HostProfileRoute
  '/host/scan': typeof HostScanRoute
  '/host/tonight': typeof HostTonightRoute
  '/host/wallet': typeof HostWalletRoute
  '/outlet/billing': typeof OutletBillingRoute
  '/outlet/bookings': typeof OutletBookingsRoute
  '/outlet/history': typeof OutletHistoryRoute
  '/outlet/profile': typeof OutletProfileRoute
  '/outlet/ratings': typeof OutletRatingsRoute
  '/outlet/sales': typeof OutletSalesRoute
  '/agency/': typeof AgencyIndexRoute
  '/host/': typeof HostIndexRoute
  '/outlet/': typeof OutletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/agency/history': typeof AgencyHistoryRoute
  '/agency/live': typeof AgencyLiveRoute
  '/agency/pending': typeof AgencyPendingRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/agency/prs': typeof AgencyPrsRoute
  '/agency/pv': typeof AgencyPvRoute
  '/agency/reports': typeof AgencyReportsRoute
  '/agency/roster': typeof AgencyRosterRoute
  '/host/history': typeof HostHistoryRoute
  '/host/profile': typeof HostProfileRoute
  '/host/scan': typeof HostScanRoute
  '/host/tonight': typeof HostTonightRoute
  '/host/wallet': typeof HostWalletRoute
  '/outlet/billing': typeof OutletBillingRoute
  '/outlet/bookings': typeof OutletBookingsRoute
  '/outlet/history': typeof OutletHistoryRoute
  '/outlet/profile': typeof OutletProfileRoute
  '/outlet/ratings': typeof OutletRatingsRoute
  '/outlet/sales': typeof OutletSalesRoute
  '/agency': typeof AgencyIndexRoute
  '/host': typeof HostIndexRoute
  '/outlet': typeof OutletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRouteWithChildren
  '/host': typeof HostRouteWithChildren
  '/outlet': typeof OutletRouteWithChildren
  '/signin': typeof SigninRoute
  '/agency/history': typeof AgencyHistoryRoute
  '/agency/live': typeof AgencyLiveRoute
  '/agency/pending': typeof AgencyPendingRoute
  '/agency/profile': typeof AgencyProfileRoute
  '/agency/prs': typeof AgencyPrsRoute
  '/agency/pv': typeof AgencyPvRoute
  '/agency/reports': typeof AgencyReportsRoute
  '/agency/roster': typeof AgencyRosterRoute
  '/host/history': typeof HostHistoryRoute
  '/host/profile': typeof HostProfileRoute
  '/host/scan': typeof HostScanRoute
  '/host/tonight': typeof HostTonightRoute
  '/host/wallet': typeof HostWalletRoute
  '/outlet/billing': typeof OutletBillingRoute
  '/outlet/bookings': typeof OutletBookingsRoute
  '/outlet/history': typeof OutletHistoryRoute
  '/outlet/profile': typeof OutletProfileRoute
  '/outlet/ratings': typeof OutletRatingsRoute
  '/outlet/sales': typeof OutletSalesRoute
  '/agency/': typeof AgencyIndexRoute
  '/host/': typeof HostIndexRoute
  '/outlet/': typeof OutletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agency'
    | '/host'
    | '/outlet'
    | '/signin'
    | '/agency/history'
    | '/agency/live'
    | '/agency/pending'
    | '/agency/profile'
    | '/agency/prs'
    | '/agency/pv'
    | '/agency/reports'
    | '/agency/roster'
    | '/host/history'
    | '/host/profile'
    | '/host/scan'
    | '/host/tonight'
    | '/host/wallet'
    | '/outlet/billing'
    | '/outlet/bookings'
    | '/outlet/history'
    | '/outlet/profile'
    | '/outlet/ratings'
    | '/outlet/sales'
    | '/agency/'
    | '/host/'
    | '/outlet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/agency/history'
    | '/agency/live'
    | '/agency/pending'
    | '/agency/profile'
    | '/agency/prs'
    | '/agency/pv'
    | '/agency/reports'
    | '/agency/roster'
    | '/host/history'
    | '/host/profile'
    | '/host/scan'
    | '/host/tonight'
    | '/host/wallet'
    | '/outlet/billing'
    | '/outlet/bookings'
    | '/outlet/history'
    | '/outlet/profile'
    | '/outlet/ratings'
    | '/outlet/sales'
    | '/agency'
    | '/host'
    | '/outlet'
  id:
    | '__root__'
    | '/'
    | '/agency'
    | '/host'
    | '/outlet'
    | '/signin'
    | '/agency/history'
    | '/agency/live'
    | '/agency/pending'
    | '/agency/profile'
    | '/agency/prs'
    | '/agency/pv'
    | '/agency/reports'
    | '/agency/roster'
    | '/host/history'
    | '/host/profile'
    | '/host/scan'
    | '/host/tonight'
    | '/host/wallet'
    | '/outlet/billing'
    | '/outlet/bookings'
    | '/outlet/history'
    | '/outlet/profile'
    | '/outlet/ratings'
    | '/outlet/sales'
    | '/agency/'
    | '/host/'
    | '/outlet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRouteWithChildren
  HostRoute: typeof HostRouteWithChildren
  OutletRoute: typeof OutletRouteWithChildren
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet': {
      id: '/outlet'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof OutletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet/': {
      id: '/outlet/'
      path: '/'
      fullPath: '/outlet/'
      preLoaderRoute: typeof OutletIndexRouteImport
      parentRoute: typeof OutletRoute
    }
    '/host/': {
      id: '/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof HostIndexRouteImport
      parentRoute: typeof HostRoute
    }
    '/agency/': {
      id: '/agency/'
      path: '/'
      fullPath: '/agency/'
      preLoaderRoute: typeof AgencyIndexRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/outlet/sales': {
      id: '/outlet/sales'
      path: '/sales'
      fullPath: '/outlet/sales'
      preLoaderRoute: typeof OutletSalesRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/ratings': {
      id: '/outlet/ratings'
      path: '/ratings'
      fullPath: '/outlet/ratings'
      preLoaderRoute: typeof OutletRatingsRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/profile': {
      id: '/outlet/profile'
      path: '/profile'
      fullPath: '/outlet/profile'
      preLoaderRoute: typeof OutletProfileRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/history': {
      id: '/outlet/history'
      path: '/history'
      fullPath: '/outlet/history'
      preLoaderRoute: typeof OutletHistoryRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/bookings': {
      id: '/outlet/bookings'
      path: '/bookings'
      fullPath: '/outlet/bookings'
      preLoaderRoute: typeof OutletBookingsRouteImport
      parentRoute: typeof OutletRoute
    }
    '/outlet/billing': {
      id: '/outlet/billing'
      path: '/billing'
      fullPath: '/outlet/billing'
      preLoaderRoute: typeof OutletBillingRouteImport
      parentRoute: typeof OutletRoute
    }
    '/host/wallet': {
      id: '/host/wallet'
      path: '/wallet'
      fullPath: '/host/wallet'
      preLoaderRoute: typeof HostWalletRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/tonight': {
      id: '/host/tonight'
      path: '/tonight'
      fullPath: '/host/tonight'
      preLoaderRoute: typeof HostTonightRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/scan': {
      id: '/host/scan'
      path: '/scan'
      fullPath: '/host/scan'
      preLoaderRoute: typeof HostScanRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/profile': {
      id: '/host/profile'
      path: '/profile'
      fullPath: '/host/profile'
      preLoaderRoute: typeof HostProfileRouteImport
      parentRoute: typeof HostRoute
    }
    '/host/history': {
      id: '/host/history'
      path: '/history'
      fullPath: '/host/history'
      preLoaderRoute: typeof HostHistoryRouteImport
      parentRoute: typeof HostRoute
    }
    '/agency/roster': {
      id: '/agency/roster'
      path: '/roster'
      fullPath: '/agency/roster'
      preLoaderRoute: typeof AgencyRosterRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/reports': {
      id: '/agency/reports'
      path: '/reports'
      fullPath: '/agency/reports'
      preLoaderRoute: typeof AgencyReportsRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/pv': {
      id: '/agency/pv'
      path: '/pv'
      fullPath: '/agency/pv'
      preLoaderRoute: typeof AgencyPvRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/prs': {
      id: '/agency/prs'
      path: '/prs'
      fullPath: '/agency/prs'
      preLoaderRoute: typeof AgencyPrsRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/profile': {
      id: '/agency/profile'
      path: '/profile'
      fullPath: '/agency/profile'
      preLoaderRoute: typeof AgencyProfileRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/pending': {
      id: '/agency/pending'
      path: '/pending'
      fullPath: '/agency/pending'
      preLoaderRoute: typeof AgencyPendingRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/live': {
      id: '/agency/live'
      path: '/live'
      fullPath: '/agency/live'
      preLoaderRoute: typeof AgencyLiveRouteImport
      parentRoute: typeof AgencyRoute
    }
    '/agency/history': {
      id: '/agency/history'
      path: '/history'
      fullPath: '/agency/history'
      preLoaderRoute: typeof AgencyHistoryRouteImport
      parentRoute: typeof AgencyRoute
    }
  }
}

interface AgencyRouteChildren {
  AgencyHistoryRoute: typeof AgencyHistoryRoute
  AgencyLiveRoute: typeof AgencyLiveRoute
  AgencyPendingRoute: typeof AgencyPendingRoute
  AgencyProfileRoute: typeof AgencyProfileRoute
  AgencyPrsRoute: typeof AgencyPrsRoute
  AgencyPvRoute: typeof AgencyPvRoute
  AgencyReportsRoute: typeof AgencyReportsRoute
  AgencyRosterRoute: typeof AgencyRosterRoute
  AgencyIndexRoute: typeof AgencyIndexRoute
}

const AgencyRouteChildren: AgencyRouteChildren = {
  AgencyHistoryRoute: AgencyHistoryRoute,
  AgencyLiveRoute: AgencyLiveRoute,
  AgencyPendingRoute: AgencyPendingRoute,
  AgencyProfileRoute: AgencyProfileRoute,
  AgencyPrsRoute: AgencyPrsRoute,
  AgencyPvRoute: AgencyPvRoute,
  AgencyReportsRoute: AgencyReportsRoute,
  AgencyRosterRoute: AgencyRosterRoute,
  AgencyIndexRoute: AgencyIndexRoute,
}

const AgencyRouteWithChildren =
  AgencyRoute._addFileChildren(AgencyRouteChildren)

interface HostRouteChildren {
  HostHistoryRoute: typeof HostHistoryRoute
  HostProfileRoute: typeof HostProfileRoute
  HostScanRoute: typeof HostScanRoute
  HostTonightRoute: typeof HostTonightRoute
  HostWalletRoute: typeof HostWalletRoute
  HostIndexRoute: typeof HostIndexRoute
}

const HostRouteChildren: HostRouteChildren = {
  HostHistoryRoute: HostHistoryRoute,
  HostProfileRoute: HostProfileRoute,
  HostScanRoute: HostScanRoute,
  HostTonightRoute: HostTonightRoute,
  HostWalletRoute: HostWalletRoute,
  HostIndexRoute: HostIndexRoute,
}

const HostRouteWithChildren = HostRoute._addFileChildren(HostRouteChildren)

interface OutletRouteChildren {
  OutletBillingRoute: typeof OutletBillingRoute
  OutletBookingsRoute: typeof OutletBookingsRoute
  OutletHistoryRoute: typeof OutletHistoryRoute
  OutletProfileRoute: typeof OutletProfileRoute
  OutletRatingsRoute: typeof OutletRatingsRoute
  OutletSalesRoute: typeof OutletSalesRoute
  OutletIndexRoute: typeof OutletIndexRoute
}

const OutletRouteChildren: OutletRouteChildren = {
  OutletBillingRoute: OutletBillingRoute,
  OutletBookingsRoute: OutletBookingsRoute,
  OutletHistoryRoute: OutletHistoryRoute,
  OutletProfileRoute: OutletProfileRoute,
  OutletRatingsRoute: OutletRatingsRoute,
  OutletSalesRoute: OutletSalesRoute,
  OutletIndexRoute: OutletIndexRoute,
}

const OutletRouteWithChildren =
  OutletRoute._addFileChildren(OutletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRouteWithChildren,
  HostRoute: HostRouteWithChildren,
  OutletRoute: OutletRouteWithChildren,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
